# Site settings
title: G20 Digital Hub
email: G20DETF@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
sass:
  style: compressed
exclude:
  - src
  - Gemfile
  - Gemfile.lock
  - ".gitignore"
  - node_modules
  - webpack.config.js
  - package.json
  - package-lock.json
